# this travis.yml file is for the leaderboard-nightwatch example, when run standalone
language: node_js

node_js:
  - "4.1"

services:
  - mongodb

sudo: false

env:
  global:
    - CXX=g++-4.8
    - TRAVIS=true
    - DISPLAY=:99.0
    - CONFIG_PREFIX=`npm config get prefix`
  matrix:
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
cache:
  directories:
    #- node_modules
    #- ~/.meteor
    #- ~/.meteor/local/build/programs/server/assets/packages

before_install:
  # - set CONFIG_PREFIX=`npm config get prefix`

  # - "wget https://dl.google.com/linux/direct/google-chrome-stable_current_i386.deb"
  # - "sudo apt-get update -qq"
  # - "sudo dpkg -i ./google-chrome*.deb"
  # - "sudo apt-get -f install"

  # set up the node_modules dir, so we know where it is
  - "mkdir -p node_modules &"

  # install starrynight, so we can launch nightwatch and selenium
  - "npm install -g starrynight"

  # fire up xvfb on port :99.0
  - "sh -e /etc/init.d/xvfb start"

  # set the xvfb screen size to 1280x1024x16
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"

  # install meteor
  - "curl https://install.meteor.com | /bin/sh"

  # give meteor a few seconds after installing
  - "sleep 5"
  - "starrynight fetch"

  - "sleep 20"
  - "starrynight generate --autoconfig"


  - "sleep 5"
  - "~/.meteor/meteor &"


  - "sleep 90"
  - "ls -la ~/.meteor/packages"

  # check that node_modules exist, and what's inside
  #- "echo $(npm config get prefix)/lib/node_modules"
  #- "ls -la $(npm config get prefix)/lib/node_modules"


# we're not installing starrynight globally, so we run the script from the local node_modules folder
#script: "starrynight run-tests --framework nightwatch --env travis"



script: "starrynight run-tests --framework nightwatch --env travis"
